// Code generated by cmd/lexgen (see Makefile's lexgen); DO NOT EDIT.

package noise

// schema: app.noise.modulation.level

import (
	comatprototypes "github.com/bluesky-social/indigo/api/atproto"
	"github.com/bluesky-social/indigo/lex/util"
)

func init() {
	util.RegisterType("app.noise.modulation.level", &ModulationLevel{})
} //
// RECORDTYPE: ModulationLevel
type ModulationLevel struct {
	LexiconTypeID string                         `json:"$type,const=app.noise.modulation.level" cborgen:"$type,const=app.noise.modulation.level"`
	CreatedAt     string                         `json:"createdAt" cborgen:"createdAt"`
	Level         int64                          `json:"level" cborgen:"level"`
	Subject       *comatprototypes.RepoStrongRef `json:"subject" cborgen:"subject"`
}
